apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-nfs-pvc
spec:
  storageClassName: nfs-client  # Make sure to use the correct storage class name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
